import React from 'react';

export default function Terms() {
  return (
    <div className="page-wrapper animate-fade-in" style={{ maxWidth: '840px', paddingTop: '4rem' }}>
      <div className="section-header">
        <h1>Terms of Service</h1>
        <p>Last Updated: June 20, 2026</p>
      </div>

      <div style={{ background: 'var(--bg-card)', padding: '2.5rem', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-color)' }}>
        <p className="legal-text">
          Please read these Terms of Service ("Terms") carefully before using the BATON mobile application or desktop connector software ("Application"). By installing or using BATON, you agree to be bound by these Terms.
        </p>

        <h2 className="legal-header">1. SCOPE OF SERVICE</h2>
        <p className="legal-text">
          BATON is an orchestration client and encrypted network bridge that allows users to communicate with local and remote AI models via Model Context Protocol (MCP) tunnels and WebRTC relays. BATON does not host or curate the AI models, weights, or third-party datasets executing on your machines.
        </p>

        <h2 className="legal-header">2. USER RESPONSIBILITY & ENDPOINTS</h2>
        <ul className="legal-list">
          <li><strong>Endpoint Configuration:</strong> You are solely responsible for configuring, securing, and maintaining the access credentials for the MCP tools and LLM servers you connect to the Application.</li>
          <li><strong>Carrier Bandwidth:</strong> Relay data transfers may consume cellular bandwidth. You are responsible for all standard carrier data fees.</li>
        </ul>

        <h2 className="legal-header">3. DISCLAIMER OF WARRANTIES</h2>
        <ul className="legal-list">
          <li>THE APPLICATION IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED.</li>
          <li>WE DO NOT GUARANTEE THE FACTUAL ACCURACY, COMPLETENESS, OR FITNESS FOR A PARTICULAR PURPOSE OF RESPONSES GENERATED BY CONNECTED AI MODELS.</li>
        </ul>

        <h2 className="legal-header">4. LIMITATION OF LIABILITY</h2>
        <ul className="legal-list">
          <li>TO THE MAXIMUM EXTENT PERMITTED BY LAW, BATON TECHNOLOGIES AND ITS MAINTAINERS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM THE USE OF THE SOFTWARE.</li>
          <li>YOU ASSUME FULL RESPONSIBILITY FOR ANY ACTIONS TAKEN, CODE EXECUTED, OR DECISIONS MADE BASED ON OUTPUTS PRODUCED BY CONNECTED AGENTS.</li>
        </ul>

        <h2 className="legal-header">5. EVIDENTIARY ARCHIVES & JURISDICTION</h2>
        <p className="legal-text">
          BATON provides cryptographic tools (Merkle Tree hash chains, hardware-backed signatures) designed to support digital evidence frameworks. The developers provide no legal advice; you are solely responsible for ensuring exported archives satisfy local legal admissibility criteria.
        </p>

        <h2 className="legal-header">6. MODIFICATIONS</h2>
        <p className="legal-text">
          We reserve the right to modify these Terms at any time. Continued use of the Application following updates signifies acceptance of revised terms.
        </p>
      </div>
    </div>
  );
}
