import React from 'react';
import { Link } from 'react-router-dom';

const Terms = () => {
  return (
    <div className="inner-page">
      <h1>Terms of Service</h1>
      <p className="page-intro">
        Last Updated: August 14, 2026
      </p>
      
      <p>
        Welcome to BATON. These Terms of Service ("Terms") govern your use of the BATON mobile application, desktop client, and related services (collectively, the "Service"). The Service is operated by Ekam Baton ("BATON," "we," "us," or "our").
      </p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By downloading, installing, or using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.
      </p>
      <p>
        <strong>Age Requirements:</strong> You must be at least 13 years old to use the Service (to comply with COPPA). If you are a resident of the United Arab Emirates (UAE), you must be at least 18 years old. If you are under 18 and a resident of India, you must have verifiable parental consent in accordance with the Digital Personal Data Protection Act (DPDPA).
      </p>

      <h2>2. Description of Service</h2>
      <p>
        BATON is a routing intermediary application that connects your mobile device to AI models running on your local computer via encrypted channels.
      </p>
      <ul>
        <li><strong>Local Connection:</strong> Direct Local Area Network (LAN) connection when devices are on the same network.</li>
        <li><strong>Remote Connection:</strong> A zero-knowledge relay server facilitates remote connections when outside your local network.</li>
        <li><strong>Model Context Protocol:</strong> The Service supports MCP tool server integration.</li>
      </ul>
      <p>
        BATON is strictly a routing intermediary. We do not provide, host, or curate the AI models themselves.
      </p>

      <h2>3. User Responsibilities</h2>
      <p>
        You are solely responsible for:
      </p>
      <ul>
        <li>The selection, configuration, and operation of the AI models you connect to via BATON.</li>
        <li>All inputs (prompts) and outputs generated by your selected AI models.</li>
        <li>Securing your own hardware, local network, and local AI models.</li>
        <li>Ensuring that your use of the Service complies with all applicable local, state, national, and international laws.</li>
      </ul>
      <p>
        You must not use the Service to generate, route, or distribute illegal content.
      </p>

      <h2>4. Acceptable Use Policy</h2>
      <p>
        You agree not to misuse the Service. Specifically, to comply with international regulations including the UAE Federal Decree-Law No. 34 of 2021, you must not use BATON to:
      </p>
      <ul>
        <li>Circumvent state censorship or lawful content restrictions.</li>
        <li>Generate, process, or route defamatory, fraudulent, or illegal content.</li>
        <li>Gain unauthorized access to computer systems, networks, or data.</li>
        <li>Distribute malware, viruses, or conduct cyberattacks.</li>
        <li>Process, route, or generate child sexual abuse material (CSAM).</li>
        <li>Generate or promote content that incites violence, terrorism, or harm to others.</li>
      </ul>

      <h2>5. Intermediary Status & Safe Harbor</h2>
      <p>
        <strong>India IT Act Section 79:</strong> BATON acts strictly as an intermediary. We do not initiate the transmission, select the receiver, or select/modify the information contained in the transmission.<br />
        <strong>US Section 230:</strong> BATON is not a publisher or speaker of any user-generated content and is not liable for content routed through the Service.
      </p>
      <p>
        Due to our end-to-end encryption (E2EE), BATON does not monitor, inspect, or store plaintext content. However, we will comply with valid, legally binding orders from competent authorities to the extent technically possible.
      </p>

      <h2>6. Intellectual Property</h2>
      <p>
        The BATON software client is open source and distributed under the Apache 2.0 License. You retain all rights, title, and interest in and to your prompts, inputs, and the resulting AI outputs. BATON claims no ownership over your content.
      </p>

      <h2>7. Subscription & Payment</h2>
      <p>
        Local (LAN) connections are provided free of charge. Remote relay access requires an active subscription.
      </p>
      <ul>
        <li>Subscriptions are billed annually.</li>
        <li><strong>Cooling-off Period:</strong> In accordance with UK consumer rights, you may cancel your subscription for a full refund within 14 days of your initial purchase, provided you have not excessively utilized the remote relay. No refunds are provided after this period.</li>
      </ul>

      <h2>8. Privacy</h2>
      <p>
        Your privacy is critical to us. BATON utilizes end-to-end encryption (X25519 key exchange, AES-256-GCM), meaning we cannot access or read your messages or AI outputs. For full details on our data practices, please review our <Link to="/privacy">Privacy Policy</Link>.
      </p>

      <h2>9. Disclaimer of Warranties</h2>
      <p>
        THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. BATON MAKES NO WARRANTIES, EXPRESS OR IMPLIED, REGARDING THE SERVICE.
      </p>
      <p>
        We do not guarantee the accuracy, reliability, or safety of any AI model you connect to, nor do we guarantee uninterrupted or error-free operation of the relay service. AI outputs are generated by third-party or local software, and it is your responsibility to verify their accuracy and safety.
      </p>

      <h2>10. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, BATON SHALL NOT BE LIABLE FOR:
      </p>
      <ul>
        <li>Any outputs generated by AI models connected through the Service.</li>
        <li>Data loss, hardware failure, or security breaches on your personal devices.</li>
        <li>Indirect, incidental, special, consequential, or punitive damages.</li>
      </ul>
      <p>
        Our total maximum liability for any claims under these Terms is capped at the total subscription fees you paid to BATON in the 12 months preceding the claim. These exclusions do not apply where prohibited by law (such as UK and EU consumer protection laws).
      </p>

      <h2>11. Indemnification</h2>
      <p>
        You agree to indemnify, defend, and hold harmless BATON and Ekam Baton from any claims, damages, liabilities, costs, and expenses (including legal fees) arising from your use of the Service, your violation of these Terms, or your violation of any third-party rights.
      </p>

      <h2>12. Termination</h2>
      <p>
        Either party may terminate this agreement at any time. We reserve the right to suspend or terminate your access to the remote relay service immediately and without notice if you violate the Acceptable Use Policy or any other provision of these Terms. Upon termination, any data stored on our relay servers (which is encrypted and inaccessible to us) will be deleted.
      </p>

      <h2>13. Governing Law & Dispute Resolution</h2>
      <p>
        <strong>Default:</strong> These Terms shall be governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts located in Chandigarh, India.
      </p>
      <ul>
        <li><strong>UK Users:</strong> Mandatory UK consumer protection laws apply, and you may bring proceedings in your local courts.</li>
        <li><strong>California Users:</strong> Your rights under the CCPA are preserved.</li>
        <li><strong>UAE Users:</strong> Disputes specific to UAE operations may be brought before the UAE federal courts.</li>
      </ul>

      <h2>14. Changes to Terms</h2>
      <p>
        We may update these Terms from time to time. We will provide a 30-day notice of material changes via our website and an in-app notification. Your continued use of the Service after the effective date of the changes constitutes your acceptance of the new Terms.
      </p>

      <h2>15. Healthcare Disclaimer (HIPAA)</h2>
      <p>
        <strong>WARNING:</strong> BATON is NOT a HIPAA-compliant platform. You must not use the Service to route, process, or store Protected Health Information (PHI) unless you have executed a separate Business Associate Agreement (BAA) with us. 
      </p>

      <h2>16. Contact Information</h2>
      <p>
        If you have questions about these Terms, or wish to report a violation, please contact us:
      </p>
      <ul>
        <li><strong>Email:</strong> ekam.baton@gmail.com</li>
        <li><strong>Website:</strong> <a href="https://ekam-baton.github.io/baton-docs/" target="_blank" rel="noopener noreferrer">https://ekam-baton.github.io/baton-docs/</a></li>
        <li><strong>Grievance Officer (India):</strong> Ekam Baton (ekam.baton@gmail.com)</li>
      </ul>
    </div>
  );
};

export default Terms;
